
name: CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build AMI
      # env:
      #   aws_access_key: ${{ secrets.aws_access_key }}
      #   aws_secret_key: ${{ secrets.aws_secret_key }}
      run: |
        sudo apt-get update
        sudo apt-get install -y packer
        sudo packer build  -var "aws_access_key=${AWS_ACCESS_KEY_ID}" -var "aws_secret_key=${AWS_SECRET_ACCESS_KEY}" ./packer/build.json
        
    - name: Terraform apply
      # env:
        # AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
      run: |
        cd terraform
        terraform init
        terraform plan -destroy -out plan.tf
        terraform apply -auto-approve plan.tf
